steps:
  - name: 'bash'
    args:
      - '-c'
      - |
        wget -P ./images/packer https://releases.hashicorp.com/packer/${_PACKER_VERSION}/packer_${_PACKER_VERSION}_linux_amd64.zip
        pwd
        ls -al

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/cloudrun-images/packer:${_PACKER_VERSION}',
      '--build-arg', 'PACKER_VERSION=${_PACKER_VERSION}',
      '--build-arg', 'PACKER_VERSION_SHA256SUM=${_PACKER_VERSION_SHA256SUM}',
      './images/packer'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/cloudrun-images/packer:${_PACKER_VERSION}']

substitutions:
  _PACKER_VERSION: 1.15.0
  _PACKER_VERSION_SHA256SUM: 2fd1149c5c6c7604ced64d7b56638af05f6b7ed3f6835182bc913ddaba1f16b8

images:
  - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/cloudrun-images/packer:latest'
  - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/cloudrun-images/packer:${_PACKER_VERSION}'
options:
  logging: CLOUD_LOGGING_ONLY